# Generated by Django 5.1.2 on 2025-05-11 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_remove_booking_unique_table_date_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_table_date_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'BOOKED')), fields=('table', 'date', 'time'), name='unique_active_table_booking'),
        ),
    ]
